version: '3'

services:
  oncall-web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DOCKER_DB_BOOTSTRAP=1
    volumes:
      - ./configs/config.docker.yaml:/home/oncall/config/config.yaml

  oncall-mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=1234

  oncall-admin:
    image: phamlamvuong/oncall-admin:0.0.1
    ports:
      - "16652:16652"
    volumes:
      - ./configs/oncall-admin/config.dev.yaml:/home/oncall/source/configs/config.dev.yaml
